build: build-tailwind
	npm run build

build-tailwind:
	npx tailwindcss -i ./src/content/styles/styles.css -o ./src/content/styles/output.css

css-factory-watch:
	npx tailwindcss -i ./src/content/styles/styles.css -o ./src/content/styles/output.css --watch
